version: '3'
services:
  web:
      build:
        dockerfile: web/Dockerfile
      container_name: web
      ports:
        - 80:80
      volumes:
        - ./app/src/public:/var/www/html/public
        - ./web/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - app
      networks:
        - ml-tool-net

  app:
    build:
      dockerfile: app/Dockerfile
    container_name: app
    volumes:
      - ./app/src:/var/www/html
    depends_on:
      - db
    networks:
      - ml-tool-net
  
  db:
    build:
      dockerfile: db/Dockerfile
    container_name: db
    environment:
      MYSQL_DATABASE: sample-db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      TZ: "Asia/Tokyo"
    ports:
      - '3306:3306'
    volumes:
      - ./.db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - ml-tool-net

networks:
  ml-tool-net:
    driver: bridge
    name: ml-tool-net